server:
  port: 8001

spring:
  application:
    name: OrderService

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/AnalyticsPlatform}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: order_service

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    default-schema: order_service

logging:
  level:
    liquibase: info
