server:
  port: 7001

spring:
  application:
    name: OrderService

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/AnalyticsPlatform}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: order_service

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    default-schema: order_service

logging:
  level:
    liquibase: info
    org.springdoc: info

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha

  openapi:
    title: Real-Time Order Analytics Platform
    description: REST API for Order Service with real-time analytics
    version: 0.0.1
    contact:
      name: API Support
      url: http://localhost:8001
    license:
      name: Apache 2.0
      url: http://www.apache.org/licenses/LICENSE-2.0.html

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: always
