package com.arunesh.OrderService.controller;

import com.arunesh.OrderService.dto.alerts.AlertResponse;
import com.arunesh.OrderService.service.AlertsService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.AllArgsConstructor;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

@RestController
@RequestMapping("/alerts")
@AllArgsConstructor
@Tag(name = "Alerts", description = "Alert Management APIs")
public class AlertsController {
    private final AlertsService service;

    @GetMapping
    @Operation(summary = "Get all alerts", description = "Retrieves a list of all alerts generated by the analytics system")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Alerts retrieved successfully",
                    content = @Content(mediaType = MediaType.APPLICATION_JSON_VALUE, schema = @Schema(implementation = AlertResponse.class))),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    public List<AlertResponse> getAlerts() {
        return service.getAlerts();
    }
}
